In [1]:
import numpy as np
import pandas as pd
import gc
import time

from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split

from tqdm import tqdm

import warnings
from time import time

In [2]:
%%time
train = pd.read_csv('../../TPS_2021/input/tabular-playground-series-oct-2021/train.csv')
test = pd.read_csv('../../TPS_2021/input/tabular-playground-series-oct-2021/test.csv')

CPU times: user 25.3 s, sys: 1.92 s, total: 27.2 s
Wall time: 27.2 s

In [3]:
train.head()

,id,f0,f1,f2,f3,f4,f5,f6,f7,f8,...,f276,f277,f278,f279,f280,f281,f282,f283,f284,target
0,0,0.205979,0.410993,0.176775,0.223581,0.423543,0.476140,0.413590,0.612021,0.534873,...,0,1,0,0,0,0,0,0,0,1
1,1,0.181004,0.473119,0.011734,0.213657,0.619678,0.441593,0.230407,0.686013,0.281971,...,0,1,0,0,0,0,0,0,0,1
2,2,0.182583,0.307431,0.325950,0.207116,0.605699,0.309695,0.493337,0.751107,0.536272,...,0,0,0,1,1,0,0,0,0,1
3,3,0.180240,0.494592,0.008367,0.223580,0.760618,0.439211,0.432055,0.776147,0.483958,...,0,0,0,0,1,0,0,0,0,1
4,4,0.177172,0.495513,0.014263,0.548819,0.625396,0.562493,0.117158,0.561255,0.077115,...,0,1,1,0,1,0,0,1,0,1

In [4]:
features = train.columns[1:-1]

In [5]:
target = train[['target']].values
train.drop(['target', 'id'], axis=1, inplace=True)
test.drop(['id', ], axis=1, inplace=True)

In [6]:
%%time
train_test = pd.concat([train, test], axis =0)
RS = RobustScaler()
RS.fit(train_test)
del train_test
gc.collect()
gc.collect()
train[features] = RS.transform(train)
test[features] = RS.transform(test)
del RS
gc.collect()
gc.collect()

CPU times: user 38.4 s, sys: 30.5 s, total: 1min 8s
Wall time: 1min 9s

0

In [7]:
train.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f275,f276,f277,f278,f279,f280,f281,f282,f283,f284
0,0.034955,-0.300892,0.510947,-0.574567,-0.862255,0.773671,-0.010159,-0.483174,0.274128,-0.608673,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.482222,0.155508,-0.522238,-0.713797,0.368628,0.353927,-1.143163,0.473067,-1.026526,0.070124,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.449525,-1.061695,1.444807,-0.805564,0.280900,-1.248624,0.483084,1.314314,0.281323,0.429593,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
3,-0.498043,0.313256,-0.543312,-0.574581,1.253124,0.324986,0.104049,1.637920,0.012276,0.236649,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,-0.561575,0.320022,-0.506403,3.988384,0.404512,1.822854,-1.843619,-1.139251,-2.080084,-0.526619,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [8]:
xgtrain, xgval, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=42)

In [9]:
xgtrain['target'] = y_train
xgval['target'] = y_val

In [10]:
xgtrain.to_csv('../../TPS_2021/input/tabular-playground-series-oct-2021/xgtrain.csv', index=False)
xgval.to_csv('../../TPS_2021/input/tabular-playground-series-oct-2021/xgval.csv', index=False)